### ISSUE TITLE
Checkout selected item or all item?

### ISSUE THREAD

**Issue by dualsh0ck** [pearlxcore/ShopeeAutobuyBot#30]
```
[12:48:21] Countdown started..
[12:49:55] Cart page loaded.
[12:49:56] Checkout started at 2/11/2023 12:49:56 PM
[12:49:56] All items selected.
[12:49:56] User price : 10.00
[12:49:56] Cart total price : 0.00
[12:49:56] Click 'Check Out'.
[12:49:58] ShopeePay not available. Aborting..
[12:49:58] Click 'Place Order'.
[12:49:58] Click 'Place Order'.
[12:50:04] Current element : PlaceOrderButton (//button[contains(@class, 'stardust-button') and contains(text(), 'Place Order')])
An error occurred on line    at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Shopee_Autobuy_Bot.SeleniumService.WaitUrlContainString(String text)
   at Shopee_Autobuy_Bot.Services.AutoBuyService.ShopeePayPayment(): Timed out after 5 seconds
[12:50:09] Current element : PlaceOrderButton (//button[contains(@class, 'stardust-button') and contains(text(), 'Place Order')])
An error occurred on line    at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Shopee_Autobuy_Bot.SeleniumService.WaitUrlContainString(String text)
```

Hi, just want to verify, before execute the bot, do i have to clear all product(s) in cart page first?

Seems like the bot automatically selected all item in cart page instead of the product I put inside Bot.

Thanks!

**Comment by pearlxcore** [comment]
For normal/shocking/below user price mode, better clear cart first.

**Comment by dualsh0ck** [comment]
thanks!
