### ISSUE TITLE
SaleBanner Error

### ISSUE THREAD

**Issue by dualsh0ck** [pearlxcore/ShopeeAutobuyBot#31]
```
[01:45:45] Countdown started..
[01:46:15] Product page loaded.
[01:46:20] Current element : SaleBanner (//div[contains(@class, 'O4v6r9')])
An error occurred on line    at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at Shopee_Autobuy_Bot.SeleniumService.GetElement(By locator)
   at Shopee_Autobuy_Bot.Services.AutoBuyService.IsProductAvailable()
   at Shopee_Autobuy_Bot.Services.AutoBuyService.BuyProduct(String buyMode)
   at Shopee_Autobuy_Bot.Services.AutoBuyService.ProductPage(String buyMode): no such element: Unable to locate element: {"method":"xpath","selector":"//button[contains(@class, 'btn btn-solid-primary btn--l') and contains(text(), 'buy now')]"}
  (Session info: chrome=119.0.6045.106)
```

Is this related to SaleBanner error? 

Also SaleBanner refer to which element in Product Page?

Thanks!

**Comment by pearlxcore** [comment]
![image](https://github.com/pearlxcore/Shopee-Autobuy-Bot/assets/36906814/f00f157e-e902-4863-960b-ff5e339bafab)
